### Data

This dataset is a wine enthusiast rating dataset from **Kaggle** and contains approximately 130k wine reviews. 
We could read the data in R via the following steps:

* wine_ratings <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-28/winemag-data-130k-v2.csv")

The data presents information about the variety, origin, and price of the wine, as well as the names of the tasters and their ratings and descriptions of the wines they tasted.


### Purpose

I designed this app for the purpose as follows:

a. show the relationship between wine varieties and average points for different countries, and to better present the results I also added errorbar to show confidence intervals for the average wine scores, and the other plot show the relationship between wine varieties and prices for different countries

b. use a box plot to show the relationship between wine price and points for different countries

c. create a wordcloud to visualize textual information based on tasters' descriptions of wine flavors and textures
 
d. visualize the variation of sentiment analysis scores with wine points for different countries using a density plot

According to the plots generated by the data visualization, it can be seen that the higher the price, the higher the point of the wine and the better the description made by the corresponding taster.


### Introduction

The app uses interactive components to select to view different plots and their different elements. For example: 

a. click on a row of controls at the top of a web page to view images of different analysis themes

b. on the left side of the page there is a drop-down control where users can filter the countries they want to know about

c. then, there is a set of controls related to the wordcloud, where the user can determine the parameters of the wordcloud and choose the preferred shape of the wordcloud


### Creator

Gui Gao (ggao0005@student.monash.edu)

<details>
<summary>Session information</summary>
```{r, echo = FALSE}
sessioninfo::session_info()
```
</details>
